Core - created display name heuristic
CESNET/perun pull request #2875
Opened 2020-08-31 11:50 UTC by Vojtech-Sassmann

* The old ....

2020-08-31 11:51 UTC, balcirakpeter requested changes
Please add commit message

2020-09-02 10:52 UTC, balcirakpeter approved these changes
Just the typo, otherwise ok.

2020-09-02 10:52 UTC, balcirakpeter commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +	private Pattern getNamesPatter(String firstName, String lastName) {
Typo getNamesPatter

2020-09-02 12:56 UTC, balcirakpeter approved these changes

2020-09-03 08:20 UTC, zlamalp requested changes

2020-09-07 10:45 UTC, Vojtech-Sassmann commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
>  						updateUserNameTitles(app);
We actually want to make some bigger changes to the logic of parsing names. So I think this won't be necessary right now, or we can fix that in some other PR.

2020-09-07 10:45 UTC, Vojtech-Sassmann commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +	private static final String FED_GIVEN_NAME = "givenName";
I have used the old constants.

2020-09-07 10:51 UTC, zlamalp approved these changes

2020-09-07 10:53 UTC, merged