Added getUsersSubjects to ExtSources
CESNET/perun pull request #2876
Opened 2020-08-31 20:01 UTC by metodej

- method getUsersSubjects is now implemented everywhere where getGroupSubjects is
- query used by this method should be defined in perun-extSources.xml
- method to get http connection separated to protected method for better testing in ExtSourceISMU, also some other methods accessibility changed to protected to be mocked in tests
- also added tests for this method

2020-09-02 12:00 UTC, balcirakpeter requested changes

2020-09-02 12:53 UTC, stavamichal approved these changes

2020-09-03 15:58 UTC, metodej commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceVOOT.java
> +			return getUsersFromRemote(getGroupsFromRemote(), 0);
Ok, the method returns empty list now.

2020-09-04 07:05 UTC, balcirakpeter approved these changes

2020-09-04 07:05 UTC, merged