Core - new method to create service user
CESNET/perun pull request #2880
Opened 2020-09-02 09:19 UTC by Vojtech-Sassmann

* Created new method createServiceUser which can be used to create a
service user without any members.

2020-09-02 12:51 UTC, balcirakpeter approved these changes

2020-09-02 12:51 UTC, balcirakpeter commented on perun-base/src/main/resources/perun-roles.yml
> +    policy_roles:
```suggestion
    policy_roles: []
```

2020-09-02 12:59 UTC, Vojtech-Sassmann commented on perun-base/src/main/resources/perun-roles.yml
> +    policy_roles:
Fixed.

2020-09-04 06:57 UTC, zlamalp requested changes

2020-09-04 06:57 UTC, zlamalp commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
> +		System.out.println(CLASS_NAME + "testCreateServiceUserSetsAttributes");
```suggestion
		System.out.println(CLASS_NAME + "testCreateServiceUserSetsUes");
```

2020-09-04 06:57 UTC, zlamalp commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
> +		System.out.println(CLASS_NAME + "testCreateServiceUserSetsAttributes");
```suggestion
		System.out.println(CLASS_NAME + "testCreateServiceUserFailsForAlreadyExistingUes");
```

2020-09-07 10:47 UTC, Vojtech-Sassmann commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
> +		System.out.println(CLASS_NAME + "testCreateServiceUserSetsAttributes");
Fixed.

2020-09-07 10:47 UTC, Vojtech-Sassmann commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
> +		System.out.println(CLASS_NAME + "testCreateServiceUserSetsAttributes");
Fixed.

2020-09-07 10:58 UTC, zlamalp approved these changes

2020-09-07 10:58 UTC, merged