TODO
CESNET/perun pull request #2891
Opened 2020-09-09 13:46 UTC by Vojtech-Sassmann

2020-09-13 13:20 UTC, balcirakpeter requested changes

2020-09-13 13:20 UTC, balcirakpeter commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
> +		System.out.println(CLASS_NAME + "getEnrichedResourceByIdWithAllAttributes");
```suggestion
		System.out.println(CLASS_NAME + "getEnrichedResourceByIdWithGivenAttributes");
```

2020-09-13 13:20 UTC, balcirakpeter commented on perun-openapi/openapi.yml
> +      operationId: getEnrichedResourcesForFacility
```suggestion
      operationId: getEnrichedResourcesForVo
```

2020-09-13 13:20 UTC, balcirakpeter commented on perun-openapi/openapi.yml
> +      operationId: getEnrichedResourcesForVo
```suggestion
      operationId: getEnrichedResourcesForFacility
```

2020-09-14 11:18 UTC, stavamichal commented
There is a typo in commit message.

2020-09-14 11:33 UTC, Vojtech-Sassmann commented
> There is a typo in commit message.

Yeah, the whole message seemed pretty messed up. I have rewritten it.

2020-09-14 11:38 UTC, stavamichal requested changes

2020-09-14 11:38 UTC, stavamichal commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
> +		return filterOnlyAllowedAttributes(sess, convertToEnrichedResource(sess, resource, attrNames));
This is not the right place for filtering. On the business logic layer, you need to get always all objects you could have. Filtrations need to be done on entry layer.

2020-09-15 07:58 UTC, stavamichal approved these changes

2020-09-15 08:42 UTC, balcirakpeter approved these changes

2020-09-15 08:43 UTC, merged