New role TrustedFacilityAdmin
CESNET/perun pull request #2902
Opened 2020-09-14 15:20 UTC by HejdaJakub

* I created new role TrustedFacilityAdmin (in task named TrustedFacilityManager).
* User with this role is able to assign group(s) to resource(s) and remove group(s) from resource(s) for any facility in the specific VO. Trusted facility admin has privileges to set roles like ResourceAdmin and ResourceSelfService.

2020-09-15 08:31 UTC, balcirakpeter requested changes
Please allow for the new role also this policy:
copyGroups_Resource_Resource_policy (need to have TrustedFacility and Facility admin)

2020-09-15 08:31 UTC, balcirakpeter commented on perun-base/src/main/resources/perun-roles.yml
> +      - TRUSTEDFACILITYADMIN:
```suggestion
      - TRUSTEDFACILITYADMIN: Vo
```

2020-09-15 10:57 UTC, Vojtech-Sassmann approved these changes
Except for the things mentioned by @balcirakpeter, I think it is ok.

2020-09-16 08:17 UTC, balcirakpeter approved these changes

2020-09-16 08:17 UTC, merged