Searching for users by strings with spaces
CESNET/perun pull request #2924
Opened 2020-10-09 09:46 UTC by cuadradek

- This is fix for outcome of quickfix in #2915. Quickfix caused that when
searching for users, who have a space in one part of name (e.g. in lastName),
they were not found.
- Also when searching for user by his name in reverse order, the user was not
found.
- Now when searching by similar match, both issues were fixed.
- When searching by exact match, only the bug with spaces in one part of name
was fixed.
- Tests for searching by string with a space were added too.

2020-10-12 18:23 UTC, zlamalp approved these changes

2020-10-13 07:07 UTC, stavamichal requested changes

2020-10-13 08:40 UTC, cuadradek commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
> +			return " replace(lower("+Compatibility.convertToAscii("COALESCE(users.first_name,'') || COALESCE(users.middle_name,'') || COALESCE(users.last_name,'')")+"), ' ', '')=:nameString";
In that case shouldn't we use lower() on the right side as well? Because only the parameter itself is turned to lower case.

2020-10-13 08:42 UTC, stavamichal commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
> +			return " replace(lower("+Compatibility.convertToAscii("COALESCE(users.first_name,'') || COALESCE(users.middle_name,'') || COALESCE(users.last_name,'')")+"), ' ', '')=:nameString";
In my opinion, we should do the same operations (database operations) on both sides.

2020-10-13 11:37 UTC, stavamichal approved these changes

2020-10-13 11:38 UTC, merged