Tools for list Sponsors ana SponsoredMembers
CESNET/perun pull request #3007
Opened 2020-11-26 12:24 UTC by zoraseb

listOfMembersSponsoredByUser lists members (memberId,Name) sponsored by entered user
listOfSponsorsForMember lists sponsor (userId,Name) for entered member
setSponsorshipForMember updated to be able to set expiration of
sponsorship (validityTo option)

2020-11-26 15:00 UTC, stavamichal requested changes

2020-12-01 08:39 UTC, stavamichal reviewed
Part of this PR is still script perun-cli/listOfMembersSponsoredByUser. You should remove it by:
```
git rm listOfMembersSponsoredByUser
```

2020-12-01 08:40 UTC, stavamichal requested changes

2020-12-01 08:40 UTC, stavamichal commented on perun-cli/Perun/beans/Sponsor.pm
> +
Would be great to have more "get" method for listing sponsors (at least firstName and lastName).

2020-12-02 11:40 UTC, stavamichal approved these changes

2020-12-02 15:21 UTC, zlamalp approved these changes

2020-12-02 15:21 UTC, merged