Handle sending of JMS messages in comm thread.
CESNET/perun pull request #3113
Opened 2021-03-05 11:27 UTC by mvocu

Move sending of JMS messages into receiving thread to better handle failures and recovery in dispatcher/engine.

2021-03-07 15:02 UTC, zlamalp requested changes
It seems to be working in a runtime. Just please fix the logging.

2021-03-08 11:29 UTC, Vojtech-Sassmann approved these changes

2021-03-12 08:35 UTC, mvocu commented on perun-engine/src/main/java/cz/metacentrum/perun/engine/jms/MessageReceiver.java
> +						log.debug("Message {} for dispatcher sent.\n", message);
Fixed.

2021-03-12 10:59 UTC, zlamalp approved these changes

2021-03-12 11:00 UTC, merged