Check number of embedded groups form items
CESNET/perun pull request #3193
Opened 2021-05-04 08:17 UTC by Johaney-s

* Maximum one application form item for embedded groups is allowed in VO application
* Exception is thrown if multiple definitions are found when updating application

2021-05-04 11:18 UTC, Vojtech-Sassmann requested changes
These changes look good, but we should add the check to the `addFormItem` method as well. Also, please check if any other methods can add form items.

2021-05-04 17:54 UTC, Johaney-s commented
> These changes look good, but we should add the check to the `addFormItem` method as well. Also, please check if any other methods can add form items.

Thanks, I added the check also to `addFormItem` and `copyItems`.

2021-05-04 20:49 UTC, balcirakpeter approved these changes

2021-05-12 07:42 UTC, Vojtech-Sassmann approved these changes

2021-05-12 07:42 UTC, merged