Solve conflict for init and embed group applications
CESNET/perun pull request #3199
Opened 2021-05-05 14:35 UTC by Johaney-s

* If init application to group exists, embedded won't be submitted
* Solves only conflicts for manual approval of VO applications

2021-05-05 15:14 UTC, Vojtech-Sassmann requested changes
It looks good, I have just found some places where minor improvements could be performed.

2021-05-05 15:14 UTC, Vojtech-Sassmann commented on perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
> +		registrarManager.updateForm(session, form);
This probably doesn't change anything?

2021-05-05 15:14 UTC, Vojtech-Sassmann commented on perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
> +		// prepare group application and approve
This comment makes it a little bit confusing what is actually approved.
```suggestion
		// prepare group application and approve vo application
```

2021-05-06 14:01 UTC, Vojtech-Sassmann approved these changes

2021-05-07 06:25 UTC, balcirakpeter approved these changes

2021-05-07 06:26 UTC, merged