Password manager for mu-adm namespace
CESNET/perun pull request #3245
Opened 2021-06-09 07:49 UTC by bodnara

* created password manager module for mu-adm namespace with simple login and password check

2021-06-10 08:24 UTC, Vojtech-Sassmann requested changes

2021-06-10 08:24 UTC, Vojtech-Sassmann commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuadmPasswordManagerModule.java
> +		}
I think we should add here something more complex. At least force the length of the password to be higher than 10. You can take a look at the `EinfraPasswordManagerModule` for inspiration.

2021-06-10 14:14 UTC, Vojtech-Sassmann commented
@bodnara Please, also add this constructor to the module: 

```Java
	public MuadmPasswordManagerModule() {
		actualLoginNamespace = "mu-adm";

		if (!binTrue.equals(this.passwordManagerProgram)) {
			passwordManagerProgram += "." + actualLoginNamespace;
		}
	}
```

2021-06-11 06:57 UTC, balcirakpeter approved these changes

2021-06-11 07:58 UTC, Vojtech-Sassmann approved these changes

2021-06-11 07:59 UTC, merged