Added attribute modules for o365 sendAs/onBehalf
CESNET/perun pull request #3259
Opened 2021-06-17 13:00 UTC by metodej

- added modules for storing ids of subgroups that check whether there are indeed ids of subgroups stored
- added virtual modules that calculates whether member has right to send as or on behalf of groups
- also added tests for the check and the calculation

2021-06-18 10:16 UTC, Johaney-s requested changes
Really nice piece of code, only small suggestions from me :)

2021-06-21 06:35 UTC, metodej commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365SendOnBehalfGroups.java
> +		for (String groupId : attribute.valueAsList()) {
Fixed.

2021-06-21 06:35 UTC, metodej commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365SendAsGroups.java
> +		for (String groupId : attribute.valueAsList()) {
Fixed.

2021-06-21 06:35 UTC, metodej commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ModulesUtilsBlImpl.java
> +				if (sess.getPerunBl().getGroupsManagerBl().getGroupMembers(sess, subgroup).contains(member)) {
Fixed.

2021-06-21 06:35 UTC, metodej commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ModulesUtilsBlImpl.java
> +			if (sendAs.getValue() != null && sendAs.valueAsBoolean()) {
Added check.

2021-06-21 07:17 UTC, Johaney-s approved these changes

2021-06-22 08:48 UTC, cuadradek reviewed
I think we should add tests also for each attribute module. What do you think @metodej?

2021-06-22 09:23 UTC, metodej commented
> 
> 
> I think we should add tests also for each attribute module. What do you think @metodej?

I did not think it necessary since the shared methods are tested in `ModulesUtilsEntryIntegrationTest` and the modules pretty much just call these methods. But I guess I could add a test of that syntax check for the two modules,,,

2021-06-22 12:52 UTC, cuadradek approved these changes

2021-06-24 07:11 UTC, merged