feat: method assignGroupToResource() and its variants support both sy…
CESNET/perun pull request #3287
Opened 2021-07-15 09:08 UTC by Kuliak

…nc/async modes

RPC level checks presence of "async" parameter in provided params and reads it
(in case of missing parameter, default false value is used).
New parameter added into assignGroupToResource() method signatures in entry and bl level,
where it is promoted from rpc level and promoted higher.
BL level ensures sync/async mode itself -- GroupResourceStatus value combined with activateGroupResourceAssignment() method.

2021-07-16 05:33 UTC, cuadradek requested changes

2021-07-16 05:33 UTC, cuadradek commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
> +				activateGroupResourceAssignment(perunSession, g, resource, async);
I think it is a good idea to reuse `activateGroupResourceAssignment` method, but now the same activation process (setting attributes,..) would be actually performed twice - once in `assignGroupsToResource` before this for cycle and once in `activateGroupResourceAssignment`. So consider using just `activateGroupResourceAssignment`. Also, be aware that this method silently skips activating assignments in `ACTIVE` state.

2021-07-16 06:22 UTC, Johaney-s commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
> +		resourcesManager.assignGroupToResource(sess, group, resource, false);
The build is not passing because of line 659, where the same parameter needs to be added.

2021-07-16 12:49 UTC, Johaney-s commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
> +			boolean async = parms.contains("async") ? parms.readBoolean("async") : false;
I think the new parameter should be also added to these methods in `openapi` so that we can call it with the parameter from GUI.

2021-07-21 13:02 UTC, Kuliak commented
Changes moved to https://github.com/CESNET/perun/pull/3291

2021-07-21 13:02 UTC, closed without merging