feat(core): adjustment for generated passwords for Einfra and MU
CESNET/perun pull request #3288
Opened 2021-07-16 12:44 UTC by Kuliak

Einfra -- 12 digits long passwords, without characters that can be mistaken for another
(iI, yY, oO, zZ, 0, 1), without special characters (except for dot('.') and comma(','))
MU -- 12 digits long passwords, without characters that can be mistaken for another
(iI, yY, oO, zZ, 0, 1), without special characters (except for dot('.') and comma(','))

2021-07-16 14:45 UTC, Vojtech-Sassmann requested changes
I'm also thinking, we might add the `-` and `_`. Could you please add them as well?

2021-07-16 14:45 UTC, Vojtech-Sassmann commented on perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModuleTest.java
> +	private final Pattern EinfraPasswordContainsNotAllowedChars = Pattern.compile(".*[^ABCDEFGHJKLMNPQRSTUVWXabcdefghjkmnpqrstuvwx23456789,.].*");
In our code, we don't align the variable names, please use this formatting instead:
```suggestion
	private final int randomPasswordLength = 12;
	private final Pattern EinfraPasswordContainsNotAllowedChars = Pattern.compile(".*[^ABCDEFGHJKLMNPQRSTUVWXabcdefghjkmnpqrstuvwx23456789,.].*");
```

2021-07-16 14:45 UTC, Vojtech-Sassmann commented on perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModuleTest.java
> +public class  MuPasswordManagerModuleTest extends AbstractPerunIntegrationTest {
```suggestion
public class MuPasswordManagerModuleTest extends AbstractPerunIntegrationTest {
```

2021-07-16 14:45 UTC, Vojtech-Sassmann commented on perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModuleTest.java
> +	private final Pattern MUPasswordContainsNotAllowedChars = Pattern.compile(".*[^ABCDEFGHJKLMNPQRSTUVWXabcdefghjkmnpqrstuvwx23456789,.].*");
Same here.

2021-07-19 07:57 UTC, Johaney-s approved these changes

2021-07-21 10:44 UTC, Vojtech-Sassmann approved these changes

2021-07-21 10:47 UTC, merged