feat(core): new user virtual attribute studentIdentifiers
CESNET/perun pull request #3308
Opened 2021-08-03 15:02 UTC by Kuliak

New virtual attribute represents list of user's identifiers
in organizations (login-namespace).
Attribute contains list of values in following format:
"urn:shac:personalUniqueCode:int:esi:{institution_code}:{student_number}", where
{institution_code} -- domain of institution (e.g. muni.cz)
{student_number} -- login namespace attribute

2021-08-05 08:12 UTC, Johaney-s approved these changes

2021-08-05 08:18 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_studentIdentifiers.java
> +	extends UserVirtualAttributesModuleAbstract
I would prefer this on a single line, but it's just a suggestion.

2021-08-05 13:04 UTC, balcirakpeter requested changes

2021-08-05 13:04 UTC, balcirakpeter commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_studentIdentifiers.java
> +			.distinct()
distinct is already used in the method `getAllGroupsWhereMemberIsActive`  so you can omit it here.

2021-08-06 07:58 UTC, balcirakpeter approved these changes

2021-08-06 07:58 UTC, merged