fix(registrar): fixed sending notifications about group application creation to admins
CESNET/perun pull request #3327
Opened 2021-08-23 06:06 UTC by balcirakpeter

- Notifications about created group applications were sent immediately
  after the application was created. This was causing issues in cases
  where the user was not member of the VO yet. Administrator received a
  notification but he could not approve the group application yet. This
  was changed so it sends such notification only when the user is already
  member of the VO.

2021-08-23 07:47 UTC, Vojtech-Sassmann requested changes

2021-08-23 07:47 UTC, Vojtech-Sassmann commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +	public List<Application> getOpenApplicationsForUserInVo(PerunSession sess, Vo vo) {
Shouldn't the name be like this?
```suggestion
	public List<Application> getOpenApplicationsInVo(PerunSession sess, Vo vo) {
```

2021-08-23 11:50 UTC, balcirakpeter commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +	public List<Application> getOpenApplicationsForUserInVo(PerunSession sess, Vo vo) {
No

2021-08-24 10:01 UTC, balcirakpeter commented
I've tested the changes and everything seems to work correctly.

2021-08-24 12:46 UTC, Vojtech-Sassmann requested changes

2021-08-24 12:46 UTC, Vojtech-Sassmann commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +		Member member = null;
This is not necessary.

2021-08-24 12:46 UTC, Vojtech-Sassmann commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +	public List<Application> getOpenApplicationsForUserInVo(PerunSession sess, Vo vo) {
Ok

2021-08-24 12:58 UTC, Vojtech-Sassmann approved these changes

2021-08-24 12:58 UTC, balcirakpeter commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +		Member member = null;
Fixed

2021-08-24 13:08 UTC, merged