test(core): added tests with synchronous executor for async methods
CESNET/perun pull request #3363
Opened 2021-09-23 11:57 UTC by Johaney-s

* Asynchronous methods have to be performed synchronously to run tests
* Added tests for methods dealing with autoassigning subgroups

2021-09-24 08:19 UTC, cuadradek requested changes
Great work!

2021-09-24 08:19 UTC, cuadradek commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
> +		assertTrue(perun.getResourcesManagerBl().getAssignedResources(sess, group3).size() == 1);
```suggestion
		assertTrue(perun.getResourcesManagerBl().getAssignedResources(sess, group2).size() == 1);
```

2021-09-24 08:31 UTC, cuadradek approved these changes

2021-09-24 15:37 UTC, metodej requested changes
Code looks great, but could please you add tests of method `activateGroupResourceAssignment` in async variant as well?

2021-09-27 12:36 UTC, Johaney-s commented
> Code looks great, but could please you add tests of method `activateGroupResourceAssignment` in async variant as well?

Thanks, added `activateGroupResourceAssignmentAsync` test.

2021-09-27 14:42 UTC, metodej approved these changes

2021-09-29 06:31 UTC, merged