fix(core): add set method for attribute rights (policies)
CESNET/perun pull request #3445
Opened 2022-01-11 13:02 UTC by Kuliak

* new methods for setting attribute rights added to all corresponding layers

2022-01-12 13:50 UTC, cuadradek reviewed
Nice work. Please, add the new method to openAPI as well.

2022-01-12 13:50 UTC, cuadradek commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
> +import cz.metacentrum.perun.rpc.Api;
Unused import.

2022-01-12 13:50 UTC, cuadradek commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
> +			getAttributesManagerImpl().setAttributePolicyCollections(sess, policies, attributeId);
This line should be probably before the cycle.

2022-01-12 13:50 UTC, cuadradek commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
> +
I think we should check here whether roles of given attribute policy collections exist. Similarly like in `setAttributeRights`.

2022-01-12 13:50 UTC, cuadradek commented on perun-base/src/main/java/cz/metacentrum/perun/audit/events/AttributesManagerEvents/AttributePolicyCollectionSet.java
> +	private int attributeId;
This might be unnecessary field because `attributeId` is already part of `policyCollection`. What do you think?

2022-01-13 09:04 UTC, cuadradek requested changes

2022-01-13 09:04 UTC, cuadradek commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
> +		policies.clear();
I think clearing this list is not needed since it isn't used later.

2022-01-14 08:10 UTC, cuadradek commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
> +	 * @param policies List<AttributePolicyCollection> list of policies to set
```suggestion
	 * @param policyCollections List<AttributePolicyCollection> list of AttributePolicyCollection to set
```

2022-01-20 18:47 UTC, cuadradek requested changes

2022-01-20 18:47 UTC, cuadradek commented on perun-openapi/openapi.yml
> +      summary: "Sets attribute policy collections for an attribute definition provided in given policy collections."
When I think about it, it might be reasonable to mention that original policy collections are deleted. Same for all the layers. What do you think?

2022-01-21 00:36 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
> +				getAttributeDefinitionById(sess, apc.getAttributeId());
Isn't this the same check already done with `attributeIds` list?

2022-01-21 20:12 UTC, Johaney-s approved these changes

2022-01-24 12:55 UTC, cuadradek reviewed
One last thing - I think it will be more correct if the method runs in a nested transaction in IMPL layer. It's not necessary since we don't catch exceptions in BL layer right now, but that could change in the future. Plus, we execute multiple write commands in the IMPL layer method, hence it make sense to make a nested transaction to group them. What do you think?

2022-01-24 13:30 UTC, cuadradek approved these changes

2022-01-24 13:32 UTC, merged