fix: Vo application notifications are sent only to valid admins
CESNET/perun pull request #3465
Opened 2022-02-03 10:37 UTC by Kuliak

* added functionality to check whether each admin is a valid member of given Vo

2022-02-07 09:56 UTC, Johaney-s approved these changes

2022-02-07 09:56 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
> +		// check if given user is VALID member of VO
Looks good, just cosmetic suggestion - I'd say both comments are not necessary and can be removed.

2022-02-07 13:05 UTC, cuadradek requested changes

2022-02-07 13:05 UTC, cuadradek commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
> +				result.addAll(getUserPreferredMailsForValidMembers(registrarSession, admins, app.getVo()));
Groups can have admins assigned through a group from different VO. Therefore, we should check if they are valid in that VO, not in the application's VO. We should also check their status in the group through which they are assigned.

2022-02-09 18:07 UTC, Johaney-s requested changes

2022-02-09 18:07 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AuthzResolverImplApi.java
> +	 * Get all valid richUser administrators (both in VO and given group) for complementary object and role with specified attributes.
This comment should be added to all methods relying on this method.

2022-02-09 18:22 UTC, Johaney-s commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
> +	private List<String> getUserPreferredMailsForMembers(PerunSession sess, List<RichUser> users)
```suggestion
	private List<String> getUserPreferredMails(PerunSession sess, List<RichUser> users)
```

2022-02-10 10:17 UTC, Johaney-s approved these changes

2022-02-10 10:23 UTC, cuadradek approved these changes

2022-02-10 10:59 UTC, merged