App paging get details
CESNET/perun pull request #3469
Opened 2022-02-08 10:56 UTC by xflord

2022-02-16 12:24 UTC, Johaney-s reviewed
otherwise looks good

2022-02-17 08:13 UTC, Johaney-s approved these changes

2022-02-21 08:36 UTC, cuadradek requested changes

2022-02-21 08:36 UTC, cuadradek commented on perun-base/src/main/java/cz/metacentrum/perun/registrar/model/RichApplication.java
> +public class RichApplication extends Application {
Please, add a brief Javadoc with `@author` tag :)

2022-02-21 11:49 UTC, cuadradek approved these changes

2022-02-21 11:52 UTC, merged