fix: verify membership status before retrieving admin roles
CESNET/perun pull request #3479
Opened 2022-02-21 11:33 UTC by xflord

2022-02-22 14:04 UTC, Johaney-s requested changes
good job, i suggest marking this commit with breaking change as the previous one concerning admin rights, because we're changing existing logic

2022-02-28 08:38 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
> +	 * Gets list of all user administrators of the Facility.
I think also `getRichAdmin` methods in *ManagerMethod and openapi should be updated for the validity check of admin group members.

2022-02-28 08:56 UTC, Johaney-s commented on perun-core/src/test/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImplIntegrationTest.java
> +		PerunSession session1 = getHisSession(member1);
now we can also remove the helper `getHisSession` methods

2022-02-28 12:14 UTC, Johaney-s approved these changes

2022-03-01 11:48 UTC, Kuliak approved these changes

2022-03-01 12:46 UTC, merged