feat: add method for retrieving RichMembers for VO without user attributes
CESNET/perun pull request #3488
Opened 2022-03-07 09:32 UTC by xflord

2022-03-07 18:38 UTC, HejdaJakub requested changes
I don't think we want to change all these existing methods, especially to implementation with the new required parameter. I thought that we just want one or a few new method(s) (more than one only if we want to allow the definition of attrNames, Vo statuses, etc. - but I am not sure if we want it) with no impact on existing methods. 

According to the task definition, we want this use case only for Vos, so I think you don't have to deal with groups, too.

2022-03-08 09:14 UTC, Johaney-s requested changes
it would be nice to have a test for this.

2022-03-08 09:14 UTC, Johaney-s commented on perun-openapi/openapi.yml
> +  /json/membersManager/getRichMembersWithoutUserAttributes:
```suggestion
  /json/membersManager/getRichMembersNoUserAttributes:
```
This has to match the method name in MembersManager.

2022-03-08 09:14 UTC, Johaney-s commented on perun-openapi/openapi.yml
> +      operationId: getRichMembersWithoutUserAttributes
```suggestion
      operationId: getRichMembersNoUserAttributes
```

2022-03-08 09:14 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
> +		return getPerunBl().getMembersManagerBl().filterOnlyAllowedAttributes(sess, getMembersManagerBl().getRichMembers(sess, vo), null, true);
```suggestion
		return getPerunBl().getMembersManagerBl().filterOnlyAllowedAttributes(sess, getMembersManagerBl().getRichMembersNoUserAttributes(sess, vo), null, true);
```
we need to call the right method

2022-03-08 10:07 UTC, HejdaJakub requested changes

2022-03-08 10:07 UTC, HejdaJakub commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
> +		if (!AuthzResolver.authorizedInternal(sess, "getRichMembers_Vo_policy", vo)) {
You should also add the new method to the `perun-roles.yml`. The yml definition will be the same as `getRichMembers_Vo_policy`.
```suggestion
		if (!AuthzResolver.authorizedInternal(sess, "getRichMembersNoUserAttributes_Vo_policy", vo)) {
```

2022-03-08 12:08 UTC, Johaney-s approved these changes

2022-03-10 08:11 UTC, HejdaJakub approved these changes

2022-03-10 08:11 UTC, merged