feat: implement a method for reloading perun-apps-config.yml
CESNET/perun pull request #3493
Opened 2022-03-10 09:21 UTC by xflord

2022-03-10 13:01 UTC, Johaney-s reviewed
Looks good, I have just a few suggestions.

2022-03-10 15:54 UTC, cuadradek requested changes

2022-03-10 15:54 UTC, cuadradek commented on perun-cli/reloadAppsConfig
> +	Reloads existing configurations of branding and their respective apps as configured in /etc/perun/perun-apps-config.yml
I would omit the exact path because it is configurable. In other parts as well.

2022-03-10 15:54 UTC, cuadradek commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/ConfigManagerImpl.java
> +		Resource configPath = new PathResource("/etc/perun/perun-apps-config.yml");
Agreed, instead of creating a new loader object, I would probably inject the existing Spring bean _perunAppsConfigLoader_  into ConfigManagerImpl.

2022-03-11 07:56 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/ConfigManagerImpl.java
> +		Resource configPath = new PathResource("/etc/perun/perun-apps-config.yml");
Really good point, didn't realize this could be done.

2022-03-11 09:04 UTC, cuadradek approved these changes

2022-03-11 10:56 UTC, Johaney-s approved these changes

2022-03-11 11:01 UTC, merged