feat(openapi): added methods to OpenApi
CESNET/perun pull request #3510
Opened 2022-03-21 08:48 UTC by mattjoke

* added methods to VosManagerMethod
* added methods to OpenApi specification

2022-03-21 09:25 UTC, bodnara requested changes
All of these methods are connected to the concept of hierarchical organizations and their member organizations. So in this context adding "member" is refering to object `Vo` and not `Member`. Which I must admit, can be misleading.

2022-03-21 09:25 UTC, bodnara commented on perun-openapi/openapi.yml
> +      summary: Add member to vo.
What this method does is that it adds a `Vo` as a member of another `Vo`, rather than adding a `Member` as a "person".

2022-03-21 09:25 UTC, bodnara commented on perun-openapi/openapi.yml
> +        - $ref: '#/components/parameters/memberId'
`'#/components/parameters/voId'`

2022-03-21 09:25 UTC, bodnara commented on perun-openapi/openapi.yml
> +      summary: Remove member from vo.
Same here, we are removing `member Vo` from `Vo`

2022-03-21 09:25 UTC, bodnara commented on perun-openapi/openapi.yml
> +        - $ref: '#/components/parameters/memberId'
`'#/components/parameters/voId'`

2022-03-21 09:25 UTC, bodnara commented on perun-openapi/openapi.yml
> +        - $ref: '#/components/parameters/memberId'
`'#/components/parameters/voId'`

2022-03-21 09:33 UTC, bodnara commented
One suggestion regarding commit messages. Try to be more specific. It should be somewhat clear what was actually added.

2022-03-21 14:31 UTC, bodnara approved these changes
Seems ok like this.
I would suggest if you need some changes that are already merged to master you can just rebase your branch.

2022-03-22 08:42 UTC, xflord reviewed
I think we ideally want 1 commit per scope that's being changed (I believe you had it right on the first push, then it got a bit messy). Other than that the code seems fine.

2022-03-22 10:06 UTC, HejdaJakub approved these changes

2022-03-22 10:13 UTC, merged