feat(core): add/remove facility from consent hub
CESNET/perun pull request #3528
Opened 2022-03-30 09:13 UTC by sarkapalkovicova

Added methods for adding and removing facility from consent hub.

2022-03-31 10:13 UTC, Johaney-s reviewed
could you please add tests for the new methods?

2022-03-31 10:13 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ConsentsManagerBlImpl.java
> +import cz.metacentrum.perun.core.api.Vo;
unused imports

2022-03-31 10:13 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ConsentsManagerBlImpl.java
> +		consentsManagerImpl.removeFacility(sess, consentHub, facility);
we will want to remove whole consentHub if we removed last facility. it should replace current solution in #3528 when removing facility

2022-04-01 12:13 UTC, xflord requested changes

2022-04-01 12:13 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/bl/ConsentsManagerBl.java
> +	 * @param facility facility to be added
```suggestion
	 * @param facility facility to be removed
```

2022-04-01 12:13 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/ConsentsManagerImpl.java
> +	public void addFacility(PerunSession sess, ConsentHub consentHub, Facility facility) throws FacilityAlreadyAssigned {
Now that we have this method, we probably want to use it in FacilitiesManager in createFacility.

2022-04-01 12:13 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/ConsentsManagerEntryIntegrationTest.java
> +	public void addFacilityToConsentHubAgain() throws Exception {
I would probably include another test which covers normal behaviour of addFacility (This test **would** cover it if createFacility() used addFacility() )

2022-04-04 15:28 UTC, cuadradek reviewed
Please, add nested transactions for these two methods in impl layer. It is defined in the file `perun-core.xml`.

2022-04-04 15:28 UTC, cuadradek commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ConsentsManagerBlImpl.java
> +	public void removeFacility(PerunSession sess, ConsentHub consentHub, Facility facility) throws RelationNotExistsException, ConsentHubAlreadyRemovedException {
Now we can use this method in `FacilitiesManagerBlImpl.deleteFacility` - there is _TODO_ from #3524.

2022-04-05 06:47 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
> +import cz.metacentrum.perun.core.api.exceptions.*;
we don't use wildcard imports, please keep the original format

2022-04-05 07:20 UTC, cuadradek commented on perun-core/src/main/java/cz/metacentrum/perun/core/bl/ConsentsManagerBl.java
> +	 * Removes facility from consent hub.
Please, mention here that the consent hub is deleted if it is the last facility in the consent hub because it is a little bit unexpected behavior.

2022-04-05 07:44 UTC, cuadradek approved these changes

2022-04-05 07:51 UTC, Johaney-s approved these changes

2022-04-05 07:53 UTC, merged