feat(core): add method to update consentHub
CESNET/perun pull request #3532
Opened 2022-03-31 12:42 UTC by Johaney-s

* added method to update consentHub
* adding facilities this way is not possible

2022-04-01 08:01 UTC, HejdaJakub requested changes
It looks good, I have just a few suggestions.

2022-04-01 08:02 UTC, cuadradek requested changes

2022-04-01 11:12 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/ConsentsManagerEntry.java
> +		getConsentsManagerBl().getConsentHubById(sess, consentHub.getId());
This supposed to be a check that consentHub we're updating exists, but I agree `checkConsentHubExists` will be more clear.

2022-04-01 11:13 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/ConsentsManagerImpl.java
> +			if (consentHub.getName() == null) {
As @cuadradek noticed, it should not be allowed for updating hub, but added check for null or empty name to entry layer.

2022-04-01 11:13 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/ConsentsManagerEntry.java
> +		getConsentsManagerBl().getConsentHubById(sess, consentHub.getId());
good point, replaced

2022-04-01 11:14 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/ConsentsManagerImpl.java
> +				consentHub.setName(consentHub.getFacilities().get(0).getName());
absolutely, added the check to the entry layer

2022-04-01 11:14 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/ConsentsManagerImpl.java
> +					sess.getPerunPrincipal().getActor(), sess.getPerunPrincipal().getUserId(), consentHub.getId());
added with test for that

2022-04-01 16:21 UTC, HejdaJakub approved these changes

2022-04-04 07:52 UTC, cuadradek approved these changes

2022-04-04 08:46 UTC, merged