Dev39
CESNET/perun pull request #3558
Opened 2022-04-28 11:54 UTC by mattjoke

2022-04-29 09:21 UTC, xflord requested changes
Also update the comments/documentation in ServicesAgent.pm to include the new parameter. Some of the tests are failing, because you forgot to update them with the new consentEval parameter -  try to run relevant tests yourself before pushing.

2022-04-29 09:21 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/HierarchicalHashedDataGenerator.java
> +		if (consentEval) {
Join into one IF statement. We still want to run the code in this else block if consentEval is false.

2022-04-29 09:21 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/GroupsHashedDataGenerator.java
> +			if (consentEval) {
Join into one if statement on line 85. We want to check if we force consents globally AND for that specific service

2022-05-02 13:09 UTC, mattjoke commented on perun-cli/Perun/Agent.pm
> +});
You are right, this approach enables the consent eval in every script using Agent.pm.

2022-05-04 10:12 UTC, xflord requested changes
Also as @Johaney-s probably already told you, we need to make sure that automatic calls of services set consentEval to true (probably?). Ask around how/where this is done.

2022-05-09 07:10 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/HierarchicalHashedDataGenerator.java
> +		if (consentEval && BeansUtils.getCoreConfig().getForceConsents()) {
we\ll want to filter out members that do not have consent even if calling it without the consentEval flag, we just want to skip creation of new consents in that case

2022-05-09 07:13 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/HierarchicalHashedDataGenerator.java
> +		if (consentEval && BeansUtils.getCoreConfig().getForceConsents()) {
we'll want to filter out members that do not have consent even if calling it without the consentEval flag, we just want to skip creation of new consents in that case

2022-05-10 12:57 UTC, Johaney-s approved these changes

2022-05-11 10:03 UTC, balcirakpeter requested changes

2022-05-12 09:14 UTC, balcirakpeter requested changes
Please update also Javadoc in `ServicesAgent.pm`  for `getHashedData` subroutines.

2022-05-12 09:14 UTC, balcirakpeter commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ConsentsManagerBlImpl.java
> +		} else if (unsignedConsent == null || !unsignedConsent.getAttributes().containsAll(requiredAttributes) && consentEval) {
Please add extra parentheses so the condition is more understandable.
```suggestion
		} else if ((unsignedConsent == null || !unsignedConsent.getAttributes().containsAll(requiredAttributes)) && consentEval) {
```

2022-05-12 09:57 UTC, merged