feat(core): add force property to anonymizeUsers method
CESNET/perun pull request #3581
Opened 2022-05-11 11:36 UTC by xkureck

* add possibility to call method anonymizeUsers with force switch to remove the user from groups and vos

2022-05-12 08:51 UTC, xflord requested changes

2022-05-12 08:51 UTC, xflord commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
> +				ac.getUsersManager().anonymizeUser(ac.getSession(), ac.getUserById(parms.readInt("user")));
```suggestion
				ac.getUsersManager().anonymizeUser(ac.getSession(), ac.getUserById(parms.readInt("user")), false);
```
Maybe we can do this and keep only the version of anonymizeUser with the force parameter for cleaner code, what do you think?

2022-05-13 13:12 UTC, cuadradek approved these changes

2022-05-16 06:47 UTC, xflord approved these changes

2022-05-16 07:22 UTC, merged