feat(core): check weak passwords according to dictionary
CESNET/perun pull request #3631
Opened 2022-06-20 08:09 UTC by Johaney-s

* we can now add weak passwords dictionaries to reject weak passwords
* if no weakpass file is found, the information is logged and the check is skipped
* if namespace-specific file is not found, default one is tried
* weakpass file needs to be sorted by ASCII ordering and separated by newline

2022-06-20 08:15 UTC, Johaney-s commented
For testing:
- received example file is this one: https://weakpass.com/wordlist/1949
- the file needs to be sorted by ASCII ordering to work properly, for example: `LC_ALL=C sort --parallel=4 -uo sortedweakpass.txt weakpass.txt` and moved to` /etc/perun` as `weakpass.txt` or (namespaced version) as `weakpass_einfra.txt`
- tests that cannot be included in the PR but can be useful for review: https://gist.github.com/Johaney-s/25c653262f83463eb44349c388a71be2#file-einfrapasswordmanagermoduletest-java

2022-06-21 07:42 UTC, cuadradek reviewed
Looks good.

2022-06-21 10:30 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
> +			RandomAccessFile raf = new RandomAccessFile(filename, "r");
fixed

2022-06-21 10:35 UTC, cuadradek approved these changes

2022-06-22 07:19 UTC, xflord requested changes

2022-06-22 07:19 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
> +			//set pointer to nearest predeceasing newline to read the whole word
```suggestion
			//set pointer to nearest preceding newline to read the whole word
```

2022-06-22 07:19 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
> +				return true;
and here?

2022-06-22 07:19 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
> +				return false;
shouldn't we close the file here?

2022-06-22 07:31 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
> +				return false;
yup, fixed

2022-06-22 08:15 UTC, xflord approved these changes

2022-06-22 08:40 UTC, merged