feat(core): critical operations in GroupsManager
CESNET/perun pull request #3674
Opened 2022-08-03 14:58 UTC by sarkapalkovicova

Critical operations in perun-roles.yml were marked.

2022-08-04 06:50 UTC, Johaney-s reviewed
sometimes we'll mark the whole VO as critical and not set every group as a critical object, and because groups influence the VO itself, we should add checks also for - MFA: Vo where possible. this goes for deleting groups, extending memberships etc.

2022-08-05 07:57 UTC, Johaney-s commented on perun-base/src/main/resources/perun-roles.yml
>    synchronizeGroups_policy:
please add global MFA check here and to `synchronizeGroupsStructures_policy`

2022-08-05 07:57 UTC, Johaney-s commented on perun-base/src/main/resources/perun-roles.yml
> +      - MFA: Member
we don't need to check members in the two policies removing group unions

2022-08-05 07:57 UTC, Johaney-s commented on perun-base/src/main/resources/perun-roles.yml
> +      - MFA: Member
please add also check for Group and Vo here, changing the member's status can gain him access that is managed by group or VO...

2022-08-05 07:57 UTC, Johaney-s commented on perun-base/src/main/resources/perun-roles.yml
> +      - MFA: Vo
i'd add  `- MFA: Group` because it affects also the group.

2022-08-05 08:30 UTC, xflord requested changes

2022-08-05 08:30 UTC, xflord commented on perun-base/src/main/resources/perun-roles.yml
> +      - MFA: Group
in both of the AutoRegistration methods, we want to check Vo as well, since it affects the registration process for the Vos of the groups.

2022-08-05 08:35 UTC, Johaney-s commented
please change the base of the PR from CESNET:master to CESNET:mfa

2022-08-05 11:51 UTC, xflord approved these changes

2022-08-08 07:26 UTC, Johaney-s approved these changes

2022-08-08 07:26 UTC, merged