feat(core): add MFA role to principal roles
CESNET/perun pull request #3686
Opened 2022-08-14 11:29 UTC by Johaney-s

* MFA role signals that principal is authorized by multifactor authentication
* this is resolved by obtaining info from UserInfoEndpoint
* if the acr value matches the one expected and timestamp is not older than allowed timeout, the role is added to principal
* the role itself will be required by critical operations in perun

2022-08-15 07:54 UTC, cuadradek approved these changes

2022-08-15 10:33 UTC, xflord approved these changes

2022-08-15 10:33 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
> +			log.error("MFA auth timestamp " + returnedTimestamp + " was grater than current time");
```suggestion
			log.error("MFA auth timestamp " + returnedTimestamp + " was greater than current time");
```
typo

2022-08-15 10:48 UTC, xkureck approved these changes

2022-08-15 15:32 UTC, Johaney-s commented
changes after testing:
- renamed `userInfoEndpointAcrValue` to `userInfoEndpointMfaAcrValue`, because acr values are returned also by other authentication methods
- only MFA_TIMESTAMP is now added to additional informations if acr value matches mfa acr value, acr itself is not later needed
- it is now stored in principal's additional information so we can see updated value in `getPerunPrincipal` result, before it was only stored on creation and not updated there, separate map was used
- fixed wrong comparison of timestamp < now check
- moved retrieving issuer and access token in Api
- there's use case of delegation that is commented as fixme, we're okay keeping it out of MFA for now

2022-08-15 16:56 UTC, cuadradek approved these changes

2022-08-16 11:15 UTC, balcirakpeter requested changes
We do not need to explicitly call the `userInfoEndPoint` each time we refresh authorization. We need to retrieve information about MFA only during session refresh. Inside the authorization refresh, we work only with the given timestamp.

2022-08-16 11:17 UTC, Johaney-s commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
> +	 * The information is resolved in UserInfoEndpointCall and stored in principal's additional informations.
it is consistent with the name of the property in perun principal

2022-08-16 14:21 UTC, balcirakpeter approved these changes

2022-08-17 07:06 UTC, merged