feat(core): new method getFacilitiesByAttributeWithAttributes
CESNET/perun pull request #3714
Opened 2022-09-15 08:26 UTC by xflord

* implemented new method getFacilitiesByAttributeWithAttributes that searches for facilities by attribute and returns them along with additional chosen attributes
* added new class FacilityWithAttributes

2022-09-15 12:52 UTC, Johaney-s requested changes
seems to work fine, only a few suggestions

2022-09-15 12:52 UTC, Johaney-s commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
> +		System.out.println(perun.getAttributesManager().getAttributes(sess, facility));
probably debugging leftover

2022-09-15 12:52 UTC, Johaney-s commented on perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
> +$objectExamples{"List<FacilityWithAttributes>"} = $objectExamples{"List&lt;FacilityWithAttributes&gt;&gt;"};
```suggestion
$objectExamples{"List<FacilityWithAttributes>"} = $objectExamples{"List&lt;FacilityWithAttributes&gt;"};
```

2022-09-15 12:52 UTC, Johaney-s commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
> +		Attribute attr;
would be nice to reuse some setUp method, for example `Attribute attr = setUpAttribute1(); `, and move the try-catch block to the setUp method instead

2022-09-16 10:02 UTC, Johaney-s approved these changes

2022-09-19 10:51 UTC, sarkapalkovicova approved these changes

2022-09-19 11:27 UTC, merged