feat(core): added keepMemberStatus attribute
CESNET/perun pull request #3721
Opened 2022-09-21 16:01 UTC by sarkapalkovicova

Added attribute, which when is set to value true, statuses of existing members will not be updated during synchronization.

2022-09-22 08:49 UTC, xflord requested changes

2022-09-22 08:49 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
> +	private boolean isMemberStatusChangeAllowed(PerunSession sess, Group group) throws WrongAttributeAssignmentException, AttributeNotExistsException {
Should this method return the value of the new attribute? Seems to me that it only returns true when the attribute is not set, which doesn't make much sense. The javadocs are really confusing as well.

2022-09-23 06:16 UTC, Johaney-s approved these changes

2022-09-23 06:17 UTC, merged

2022-10-07 11:17 UTC, Johaney-s commented
We tested and discussed the intended behavior of the changes and concluded this is not the way it supposed to work, so in order to not include this in the release I'll revert the changes now and we'll reuse the attribute initialization and change the logic accordingly in new PR.