fix(cli): default OIDC config message fix
CESNET/perun pull request #3749
Opened 2022-10-17 11:09 UTC by Kuliak

* Message about usage of default OIDC config is printed only when authenticating, not every time configuration is being loaded

2022-10-18 09:25 UTC, xflord requested changes

2022-10-18 09:25 UTC, xflord commented on perun-cli/Perun/auth/OidcAuth.pm
> +		print "Environment variable PERUN_OIDC_CONFIG not set, using default config $config.\n";
This would print the message even when PERUN_OIDC_CONFIG is set to the default config, which is contradictory.

2022-10-18 09:26 UTC, xflord commented
![Screenshot from 2022-10-18 11-23-54](https://user-images.githubusercontent.com/97669007/196391933-fd1c820c-c0f0-42ee-bb3c-a997616c95e3.png)
The name of the config doesn't print correctly

2022-10-19 11:31 UTC, Johaney-s approved these changes

2022-10-20 08:37 UTC, xflord approved these changes

2022-10-20 08:37 UTC, merged