feat(core): status indirect urn
CESNET/perun pull request #3750
Opened 2022-10-18 08:07 UTC by mattjoke

* created urn, that returns if the member provided is INDIRECT

2022-10-18 08:34 UTC, bodnara commented on perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_group_attribute_def_virt_groupStatusIndirectTest.java
> +	}
This is probably not needed?

2022-10-18 08:54 UTC, bodnara approved these changes
Seems good to me.

2022-10-18 10:12 UTC, xflord requested changes

2022-10-18 10:12 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_group_attribute_def_virt_groupStatusIndirect.java
> +		attr.setType(String.class.getName());
```suggestion
		attr.setType(Boolean.class.getName());
```

2022-10-18 10:12 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_group_attribute_def_virt_groupStatusIndirect.java
> +	public void checkAttributeSyntax(PerunSessionImpl perunSession, Member member, Group group, Attribute attribute) throws WrongAttributeValueException {
Decide, do you want to use string or boolean? getAttributeValue treats the attribute as true/false and checkAttributeSyntax as "INVALID"/null.

2022-10-19 14:37 UTC, mattjoke commented
I have tested the urn. The urn successfully returns the indirect relation based on the member id.

2022-10-20 08:39 UTC, xflord approved these changes

2022-10-20 12:14 UTC, Johaney-s approved these changes

2022-10-20 13:04 UTC, merged