feat(core): support branding between new and old GUI
CESNET/perun pull request #3758
Opened 2022-10-27 11:26 UTC by Johaney-s

* Added vos field to branding config to distinguish brand to which vo belongs
* Added support for tags directing to new admin-gui in manager's notifications
* Invitations etc. coming from new GUI should be directed to correct branding (vos property in apps-config should ensure that)
* Banner in old gui should be configurable in apps-config to also follow branding rules

BREAKING CHANGE: New brand properties in perun-apps-config.yml, deprecated newAdminGuiAlert in perun-web-gui.properties moved to perun-apps-config and can be branded

2022-10-31 08:30 UTC, mattjoke approved these changes
Looks good :+1:

2022-11-04 07:19 UTC, balcirakpeter requested changes

2022-11-04 07:19 UTC, balcirakpeter commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
> +							newValue += "organizations/" + vo.getId() + "/applications/" + appId;
There is a group with an id missing in the URL if it is a group application.

2022-11-04 07:36 UTC, balcirakpeter approved these changes

2022-11-04 07:48 UTC, merged