feat(core): Enriched Bans On Vo
CESNET/perun pull request #3776
Opened 2022-11-22 14:08 UTC by mattjoke

* created EnrichedBansOnVo
* added getEnrichedBansForVo function
* added getEnrichedBansForUser function

2022-11-23 09:26 UTC, xflord requested changes

2022-11-23 09:26 UTC, xflord commented on perun-base/src/main/resources/perun-roles.yml
> +      - GROUPADMIN: Vo
Not sure about GROUPADMIN and GROUPOBSERVER, check with @bodnara which roles we need.

2022-11-23 09:26 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
> +		return vosManagerBl.getEnrichedBansForVo(sess, voId, attrNames);
Filter the attributes before returning.

2022-11-23 09:26 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
> +		return vosManagerBl.getEnrichedBansForUser(sess, userId, attrNames);
Same here

2022-11-23 09:26 UTC, xflord commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
> +	getEnrichedBansForVo {
add Javadocs

2022-11-23 09:26 UTC, xflord commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
> +	getEnrichedBansForUser{
Here as well

2022-11-24 10:04 UTC, Johaney-s reviewed
good job, i have some cosmetic, mainly java-:dog: suggestions

2022-11-25 08:28 UTC, mattjoke commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
> +	 * @return List<BanOnVo> vo bans for given group
Shouldn't there be a `vo bans for given user`?

2022-11-25 13:36 UTC, Johaney-s commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
> +	 * @return List<BanOnVo> vo bans for given group
of course :+1:

2022-11-25 13:48 UTC, Johaney-s commented on perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
> +$objectExamples{"EnrichedBanOnVo"} = "{ \"vo\" : " . $objectExamples{"Vo"} . " , \"member\" : " . $objectExamples{"RichMember"} . " , \"banOnVo\" : " . $objectExamples{"BanOnVo"} . " }";
```suggestion
$objectExamples{"EnrichedBanOnVo"} = "{ \"vo\" : " . $objectExamples{"Vo"} . " , \"member\" : " . $objectExamples{"RichMember"} . " , \"ban\" : " . $objectExamples{"BanOnVo"} . " }";
```

2022-11-28 07:58 UTC, Johaney-s approved these changes

2022-11-28 08:42 UTC, xflord approved these changes

2022-11-28 08:42 UTC, merged