feat(core): bulk methods for deleteTaskResultById, addExtSource and r…
CESNET/perun pull request #3803
Opened 2022-12-14 11:20 UTC by xflord

…emoveExtSource

* new bulk methods were created and added to RPC+openapi

2022-12-15 08:37 UTC, Johaney-s commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/TasksManagerMethod.java
> +	getDeleteTaskResultsByIds {
```suggestion
	deleteTaskResultsByIds {
```

2022-12-15 08:37 UTC, Johaney-s commented on perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/FacilityMismatchException.java
> +public class FacilityMismatchException extends PerunException {
might come in handy if this exception has facility as optional property for later usage

2022-12-15 11:59 UTC, HejdaJakub requested changes

2022-12-15 11:59 UTC, HejdaJakub commented on perun-openapi/openapi.yml
> +          required: true
You can shorten all these four methods for extsources by defining a list of ext sources between parameters, something like that:
```
    extSourceIds:
      name: "extSources[]"
      description: "list of extSource ids List<Integer>"
      in: query
      required: true
      schema:
        type: array
        items:
          type: integer
```
```suggestion
        - $ref: '#/components/parameters/extSourceIds'
```

2022-12-16 07:25 UTC, Johaney-s commented
i think we should add tests for the new methods as it's part of DoD...

2022-12-18 21:13 UTC, HejdaJakub approved these changes

2022-12-19 06:16 UTC, Johaney-s approved these changes

2022-12-19 06:18 UTC, merged