feat(core): bulk methods for removeSponsor, sponsorMember, removeUser…
CESNET/perun pull request #3804
Opened 2022-12-14 12:38 UTC by xflord

…ExtSource, removeResourceTagFromResource, assignResourceTagToResource

* new bulk methods were created and added to RPC+openapi

2022-12-15 10:47 UTC, HejdaJakub requested changes

2022-12-15 10:47 UTC, HejdaJakub commented on perun-openapi/openapi.yml
> +            type: array,
```suggestion
            type: array
```

2022-12-15 10:47 UTC, HejdaJakub commented on perun-openapi/openapi.yml
> +          required: true
These parameters should be lower in the method removeSponsor**s** instead of in the old, not bulk method removeSponsor.

2022-12-15 10:47 UTC, HejdaJakub commented on perun-openapi/openapi.yml
> +      summary: Removes ResourceRags from a resource. The ResourceTags must contain its id, voId and tagName.
```suggestion
      summary: Removes ResourceTags from a resource. The ResourceTags must contain its id, voId and tagName.
```

2022-12-15 10:47 UTC, HejdaJakub commented on perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
> +			}
You can theoretically simplify it.
```suggestion
			removeUserExtSource(sess, user, src, forceDelete);
```

2022-12-15 10:47 UTC, HejdaJakub commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
> +	sponsorMembers {
Please add also removeSponsors() to MembersManagerMethod.

2022-12-17 21:53 UTC, HejdaJakub reviewed
Just change two comments please due to consistency.

2022-12-17 21:53 UTC, HejdaJakub commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
> +	 * @param sponsorIds List<int> ids of sponsoring users that are to be removed
```suggestion
	 * @param sponsorIds List<Integer> ids of sponsoring users that are to be removed
```

2022-12-17 21:53 UTC, HejdaJakub commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
> +	 * @param userExtSources List<int> UserExtSource <code>id</code>
```suggestion
	 * @param userExtSources List<Integer> UserExtSource <code>id</code>
```

2022-12-18 14:52 UTC, sarkapalkovicova approved these changes

2022-12-18 21:04 UTC, HejdaJakub approved these changes

2022-12-19 07:28 UTC, merged