Bulk operations
CESNET/perun pull request #3809
Opened 2022-12-15 13:11 UTC by sarkapalkovicova

- GroupsManager
- OwnersManager
- FacilitiesManager

2022-12-16 12:05 UTC, Johaney-s requested changes

2022-12-16 13:16 UTC, xflord reviewed
other than the things @Johaney-s mentioned, looks good

2022-12-19 06:32 UTC, Johaney-s approved these changes

2022-12-19 07:49 UTC, xflord approved these changes

2022-12-19 07:50 UTC, merged