fix(core): unique constraint to vos shortName
CESNET/perun pull request #3873
Opened 2023-02-06 10:55 UTC by sarkapalkovicova

Dropped unique constraint to name and added a constraint to shortName instead.

2023-02-06 13:24 UTC, HejdaJakub requested changes

2023-02-06 13:24 UTC, HejdaJakub commented on perun-core/src/main/resources/postgresChangelog.txt
> +ALTER TABLE vos DROP constraint vo_u unique (name);
I think that if you drop the constraint you should just define a name without the rest of the definition part.
```suggestion
ALTER TABLE vos DROP constraint vo_u;
```

2023-02-06 13:24 UTC, HejdaJakub commented on perun-base/src/test/resources/test-schema.sql
> +insert into configurations values ('DATABASE VERSION','3.2.11');
Update also comment on the first line of this file, please.

2023-02-06 13:24 UTC, HejdaJakub commented on perun-db/postgres.sql
> +insert into configurations values ('DATABASE VERSION','3.2.11');
The same. Update also comment on the first line of this file, please.

2023-02-07 07:35 UTC, HejdaJakub approved these changes

2023-02-08 10:51 UTC, xflord reviewed
Mark the commit as breaking change, as we're updating DB (you can also add this to release notes for deployment)

2023-02-09 07:21 UTC, xflord approved these changes

2023-02-09 07:21 UTC, merged