feat(core): extend authz table with audit attributes
CESNET/perun pull request #4026
Opened 2023-08-01 16:04 UTC by kofzera

Added created_at, created_by, and created_by_uid columns to authz table and modified the inserts to include them. The setRole method modified to use prepared statement since user supplied input will be in the statement.

2023-08-03 12:14 UTC, xflord requested changes
We treat changes to the db as breaking changes and mark the commits accordingly. Please do so here as well.

2023-08-07 07:54 UTC, kofzera commented on perun-base/src/test/resources/test-schema.sql
> +						created_by varchar default user not null,
> please also add `modified_by` and `modified_at` to match the audit columns in other tables. Same for the `postgres.sql` file. Do not forget to add these to the query statements

At the initial consultation of the task, it was decided that these columns are not needed as there are no methods that update the table.

2023-08-07 09:08 UTC, xflord commented on perun-base/src/test/resources/test-schema.sql
> +						created_by varchar default user not null,
I was not aware, it is fine then

2023-08-07 09:12 UTC, xflord approved these changes
Looks good to me

2023-08-07 10:28 UTC, mattjoke approved these changes
Looks good :+1:

2023-08-08 07:21 UTC, merged