fix(core): service account skip MFA
CESNET/perun pull request #4028
Opened 2023-08-02 11:03 UTC by sarkapalkovicova

Skip MFA when user is service user.

2023-08-03 14:02 UTC, xflord approved these changes

2023-08-04 09:21 UTC, mattjoke approved these changes

2023-08-04 12:45 UTC, mattjoke requested changes
I found a bug, but I'm unsure how it relates to this problem. Whenever the MFA is turned on, I cannot log in (which is what we want, in a sense). But the problem is that the GUI would then throw an unmatched exception error. Looking at logs I can see that the error arises in checking for validity for MFA (which service account does not have).

2023-08-07 11:55 UTC, mattjoke approved these changes
Tested and appears to be working as it should.

2023-08-07 12:00 UTC, merged