feat(core): free logins when deleting login namespace attribute
CESNET/perun pull request #4037
Opened 2023-08-14 12:04 UTC by bodnara

* blocked and reserved logins are freed for given namespace

2023-08-14 12:13 UTC, dBucik commented
I am not sure this is a thing which should be done. Logins should stay blocked permanently IMO. Just imagine that after some time the namespace is re-introduced. You might argue that users will no longer have previous logins, but imagine somebody assigns a previously used login. That could mean they potentially get access to places where previously the login had access.

Instead, I would prefer if all of the active logins are blocked and stored somewhere, so we prevent running into the mentioned issue. 

But perhaps my opinion is a bit overkill? Did you have some discussion about such implications?

2023-08-15 07:57 UTC, xflord requested changes

2023-08-15 07:57 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
> +		attrDef.setNamespace("deleteNamespace");
```suggestion
		attrDef.setNamespace("urn:perun:user:attribute-def:def");
```
different kind of namespace hehe (this is also why the tests fail)

2023-08-15 07:57 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
> +			getPerunBl().getUsersManagerBl().unblockLoginsForNamespace(sess, attribute.getNamespace());
```suggestion
			getPerunBl().getUsersManagerBl().unblockLoginsForNamespace(sess, attribute.getFriendlyNameParameter());
```

2023-08-15 07:57 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
> +			getPerunBl().getUsersManagerBl().deleteReservedLoginsForNamespace(sess, attribute.getNamespace());
```suggestion
			getPerunBl().getUsersManagerBl().deleteReservedLoginsForNamespace(sess, attribute.getFriendlyNameParameter);
```

2023-08-15 11:18 UTC, bodnara commented
> I am not sure this is a thing which should be done. Logins should stay blocked permanently IMO. Just imagine that after some time the namespace is re-introduced. You might argue that users will no longer have previous logins, but imagine somebody assigns a previously used login. That could mean they potentially get access to places where previously the login had access.
> 
> Instead, I would prefer if all of the active logins are blocked and stored somewhere, so we prevent running into the mentioned issue.
> 
> But perhaps my opinion is a bit overkill? Did you have some discussion about such implications?

I don't remember a discussion about the idea of re-introducing a namespace. I think this is a good point but can't really comment about what's best. This is mostly on @balcirakpeter.

2023-08-16 07:22 UTC, xflord approved these changes

2023-08-17 11:06 UTC, balcirakpeter commented
@dBucik my thoughts... up to discussion of course.
- Deleting an attribute definition can be done only by Perun administrators, that should be aware of the consequences. Moreover, they are properly informed that by deleting the definition, all its values are deleted as well.
- The perun administrator can delete all values even from the blocked logins table, so it would not protect us from re-using the same logins; it would just move values to another place.
- If we do not want to delete all values, we probably do not want to delete the namespace at all. We can just keep it and don't use it.
- I am afraid that if we would want to re-introduce a namespace, only keeping old values blocked would not be enough. We would probably want to re-assign old values to existing users.
- Deleting a login namespace attribute definition (or any other definition or object) should be done only if we know that the definition is not used by any service. If there is a service that relies on the attribute, the definition should not be deleted.

2023-08-22 05:10 UTC, HejdaJakub approved these changes

2023-08-22 06:45 UTC, merged