feat: 🎸 RPC groupsManager/getGroupsWhereUserIsActiveMember
CESNET/perun pull request #4048
Opened 2023-08-21 15:08 UTC by dBucik

2023-08-23 02:39 UTC, HejdaJakub approved these changes

2023-08-24 01:59 UTC, HejdaJakub requested changes

2023-08-24 01:59 UTC, HejdaJakub commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +			.filter(item -> item .getFormItem().getType() != EMBEDDED_GROUP_APPLICATION
```suggestion
			.filter(item -> item.getFormItem().getType() != EMBEDDED_GROUP_APPLICATION
```

2023-08-24 01:59 UTC, HejdaJakub commented on perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
> +				|| item.getFormItem().getI18n().get(ApplicationFormItem.EN).getOptions() != null)
Shouldn't be there the AND (`&&`)? I thought you wanted to collect groups that are not in form item with type EMBEDDED_GROUP_APPLICATION **AND** also have options in English, am I right?
```suggestion
			.filter(item -> item .getFormItem().getType() != EMBEDDED_GROUP_APPLICATION
				&& item.getFormItem().getI18n().get(ApplicationFormItem.EN).getOptions() != null)
```

2023-08-24 22:53 UTC, HejdaJakub approved these changes

2023-08-28 07:22 UTC, bodnara approved these changes

2023-09-01 08:27 UTC, merged