feat(core): resend notifications method
CESNET/perun pull request #4071
Opened 2023-09-05 13:59 UTC by kofzera

Added bulk method for re-sending notifications to multiple applications at once.

2023-09-05 17:10 UTC, xflord requested changes

2023-09-05 17:10 UTC, xflord commented on perun-openapi/openapi.yml
> +                ids: { $ref: '#/components/parameters/ids' }
```suggestion
                ids: { type: array, items: { type: integer }, description: "ids of applications" }
```
something like this to make openapi parsing pass

2023-09-06 03:25 UTC, HejdaJakub approved these changes

2023-09-07 10:13 UTC, xflord approved these changes

2023-09-07 10:13 UTC, merged