feat(core): synchronize group membership status
CESNET/perun pull request #4104
Opened 2023-10-02 21:25 UTC by kofzera

- The status of a group member is also synchronized for SQL extSource
- The default value (status column not found, unknown value) is valid
- When a previously valid member is synchronized to expired the groupMembershipExpiration attr is set to current date
- When a new/current member is being set to valid the attr is set based on the group policy accordingly

2023-10-03 07:45 UTC, xflord reviewed
Will take a further look later today

2023-10-03 07:45 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
> +							candidate.setExpectedStatus(subjectFromLoginSource.get("status"));
This should work only for users that were not yet in the group - don't we want to update status for existing members as well? (Even during lightweight synchronization). Now it only validates the member, but ideally we want to check the status in the ExtSource and set accordingly.

2023-10-03 10:24 UTC, xflord requested changes
Also please add more tests - for lightweight synchro, cases where user is not a member of the VO/Group beforehand, etc.

2023-10-10 14:14 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
> +		synchronizeGroupStatus(sess, memberToUpdate, candidate.getExpectedSyncGroupStatus(), group);
This will still get called before the member gets added to the group in some cases - from `addMissingMemberWhileSynchronization` (and will fail).

2023-10-10 14:14 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
> +			(previousStatus == null || !previousStatus.equals(MemberGroupStatus.EXPIRED))) {
```suggestion
			!MemberGroupStatus.EXPIRED.equals(previousStatus)) {
```
just nitpicking at this point but this is what I meant

2023-10-12 11:54 UTC, xflord reviewed
One more test that assures that member is not added to group when not in VO and I'll be content. Other than the tests looks good, thanks.

2023-10-12 11:54 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupAndGroupStructureSynchronizationIntegrationTest.java
> +		groupWithExpiration = groupsManagerBl.createGroup(sess, vo, groupWithExpiration);
Please create a private method to setup `groupWithExpiration` since it repeats itself in most of the tests

2023-10-12 11:54 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupAndGroupStructureSynchronizationIntegrationTest.java
> +		System.out.println(CLASS_NAME + "synchronizeGroupUpdateMembershipStatus");
update the print in all of the tests

2023-10-12 11:54 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupAndGroupStructureSynchronizationIntegrationTest.java
> +	public void synchronizeGroupUpdateMembershipStatusExpirDateToNever() throws Exception {
This name does not make much sense to me

2023-10-12 11:54 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupAndGroupStructureSynchronizationIntegrationTest.java
> +		groupMembExpirAttr.setValue("2022-10-11");
setting expiration of valid member to the past is not correct

2023-10-13 06:32 UTC, kofzera commented
> One more test that assures that member is not added to group when not in VO and I'll be content. Other than the tests looks good, thanks.

Shouldn't the member be added to the group (and the VO) even if he is not in the VO beforehand? There is a test for that `synchronizeExpiredGroupStatusMemberNotInVO` and it adds the member to the group even without the recent changes.

2023-10-13 11:13 UTC, xflord approved these changes
Please include a deployment note about the possibility of status synchronization. Other than that as I said before - good job.

2023-10-26 17:15 UTC, balcirakpeter requested changes
We need to double-check (probably on review) that we want to synchronize group status in the lightweight synchronizations. Moreover, we need to check if it is ok to change the Candidate object in the OpenAPI (if it does not break something).

2023-10-26 17:15 UTC, balcirakpeter commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
> +			log.warn("Missing status column while synchronizing group {}.", group.getName());
Most synchronizations will not use the group status, therefore this message would just spam the logs. It would be probably better to remove it.

2023-10-26 17:15 UTC, balcirakpeter commented on perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
> +		if (isGroupMember(sess, group, memberToUpdate)) {
Be careful. This method checks whether the member is in the group, but it does not care if the membership type is direct or indirect. I think we care only about direct memberships.

2023-11-10 06:22 UTC, balcirakpeter approved these changes

2023-11-10 08:21 UTC, merged