feat(core): bulk-up public ssh key validation
CESNET/perun pull request #4124
Opened 2023-10-25 11:20 UTC by xflord

* validation of public ssh keys in the attributes now also includes a call of ssh-keygen
* this should catch some edge case invalid keys
* extracted the validation method to RPC to call from WUI

DEPLOYMENT NOTE: the `ssh-keygen` tool has to be available on instance machines

2023-10-25 22:00 UTC, sarkapalkovicova reviewed
I tested it, and it works. Wouldn't it be good to add a separate test for the new function in UsersManager? Now, this new validate logic seems to be covered only in tests for the attribute module. Otherwise, good job.

2023-10-26 10:28 UTC, sarkapalkovicova approved these changes

2023-10-26 12:14 UTC, mattjoke approved these changes
Looks good :+1:

2023-10-31 10:08 UTC, zlamalp requested changes

2023-11-02 14:19 UTC, xflord commented on perun-base/src/main/resources/perun-roles.yml
> +      - SELF:
removed policy check

2023-11-02 14:30 UTC, xflord commented on perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
> +			ac.getUsersManager().validateSSHKey(ac.getSession(), parms.readString("sshKey"));
fixed

2023-11-02 14:30 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_sshPublicKey.java
> +		Utils.validateSSHPublicKey(sshKey);
I checked ssh-keygen manually when writing the code, and the types matched (I believe our list was taken from ssh-keygen anyways). Couldn't find any more comprehensive list of supported types per version than [here](https://github.com/openssh/openssh-portable/blob/V_7_8_P1/ssh-keygen.c#L268-L297). It probably would be good to ensure openssh on the containers is of a certain version, this is something we spoke about on our last review meeting, so I'm not sure whether to wait for that implementation, or we can merge this in the meantime.

2023-11-03 06:35 UTC, zlamalp approved these changes

2023-11-03 06:35 UTC, zlamalp commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/SSHValidator.java
> +			throw new SSHKeyNotValidException("SSH key has to cannot be empty or null");
Nonsense (probably copy/paste) in the exception message.

2023-11-03 06:37 UTC, zlamalp commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_sshPublicKey.java
> +		Utils.validateSSHPublicKey(sshKey);
Ok, thank you for the research.

2023-11-03 14:12 UTC, merged