feat(core): add attribute modules for m365
CESNET/perun pull request #4125
Opened 2023-10-25 13:26 UTC by michalberky

* Added new attribute modules for m365LicenseGroup, m365AllowedLicensesPriorities and m365GroupName.
* Adhering to rules set in https://perunaai.atlassian.net/jira/software/projects/ST/boards/5?selectedIssue=ST-1226

2023-10-27 08:16 UTC, sarkapalkovicova commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_m365AllowedLicensesPriorities.java
> +import cz.metacentrum.perun.core.api.*;
Please do not use wildcard imports. Check also other files.

2023-10-30 13:43 UTC, xflord requested changes

2023-10-30 13:43 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_m365AllowedLicensesPriorities.java
> +			if (key == null) {
Check for null/empty values as well (more important than keys IMO)

2023-10-30 13:43 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_m365AllowedLicensesPriorities.java
> +		List<Resource> resources = fetchResourcesForFacility(perunSession, facility);
```suggestion
		List<Resource> resources = sess.getPerunBl().getFacilitiesManagerBl().getAssignedResources(sess, facility);
```
no need to complicate this, any exceptions thrown are ok as is

2023-10-30 13:43 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_m365AllowedLicensesPriorities.java
> +				perunSession, res, AttributesManager.NS_RESOURCE_ATTR_DEF + ":m365LicenseGroup");
We usually extract dependant attribute names to a constant field.
Use it then to implement the `getDependencies()` method, which is missing.

2023-10-30 13:43 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_m365AllowedLicensesPriorities.java
> +	private Attribute fetchResourceLicense(PerunSessionImpl perunSession, Resource res) throws WrongReferenceAttributeValueException {
nitpick, but you might as already return the values here, since it's all you use anyway

2023-10-30 13:43 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_m365GroupName.java
> +	private static final Pattern pattern = Pattern.compile("^[0-9A-Za-z!#$%&'*+\\-./=?^_`{|}~]*$");
I trust this

2023-10-30 13:43 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_m365LicenseGroup.java
> +				perunSession, facility, AttributesManager.NS_FACILITY_ATTR_DEF + ":m365AllowedLicensesPriorities");
Same for dependency here

2023-10-30 13:43 UTC, xflord commented on perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_m365LicenseGroup.java
> +	}
This can be removed

2023-11-01 17:55 UTC, xflord approved these changes
Last few things, but otherwise very nice. I like the thorough tests!

2023-11-01 17:55 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_m365AllowedLicensesPrioritiesTest.java
> +import static org.mockito.Mockito.*;
wildcard import

2023-11-01 17:55 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_m365AllowedLicensesPrioritiesTest.java
> +		attributeToCheck.setFriendlyName("m365AllowedLicensesPriorities:test");
Not sure why the `test` namespace is here, the attribute does not use namespaces. It should not do any harm, but no reason to have it here (same for the other test classes)

2023-11-01 17:55 UTC, xflord commented on perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_m365LicenseGroupTest.java
> +import static org.mockito.Mockito.*;
wildcard import

2023-11-09 11:05 UTC, michalberky commented
After changes in requirements for m365GroupName, it was decided that the course of action is to merge m365AllowedLicensesPriorities and m365LicenseGroup modules and leave m365GroupName out of this PR. 

A new PR will be opened containig the m365GrupName attribute module and will remain opened and unmerged so that it is moved to gitlab along with the repository and only then and there will it be closed.

2023-11-09 11:18 UTC, michalberky commented
_This last push is only fixing commit message_

2024-07-04 06:17 UTC, zlamalp commented
Code has been merge at GitLab, closing it here.

2024-07-04 06:17 UTC, closed without merging